# Generated by Django 6.0.6 on 2026-08-24 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_employee_id_to_waiter_and_cashier_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('CASHIER', 'Cashier'), ('POS', 'POS / Desk'), ('KITCHEN', 'Kitchen Staff')], default='STAFF', max_length=20),
        ),
        migrations.CreateModel(
            name='KitchenStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('pin_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_staff', to='accounts.branch')),
            ],
            options={
                'verbose_name': 'Kitchen Staff',
                'verbose_name_plural': 'Kitchen Staff',
                'ordering': ['name'],
            },
        ),
    ]
