# Generated by Django 6.0.6 on 2026-08-24 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_role_kitchenstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_terminals', to='accounts.cashier')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to='accounts.branch')),
            ],
            options={
                'verbose_name': 'POS Terminal',
                'verbose_name_plural': 'POS Terminals',
                'ordering': ['name'],
            },
        ),
    ]
