# Generated by Django 6.0.6 on 2026-08-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_posterminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Artisan Brew', max_length=255)),
                ('owner_name', models.CharField(default='Dilfa', max_length=255)),
                ('email', models.EmailField(default='dilfa@artisanbrew.com', max_length=254)),
                ('phone', models.CharField(default='+91 98765 43200', max_length=50)),
                ('gstin', models.CharField(default='29ARTBR1234F1Z9', max_length=100)),
                ('address', models.TextField(default='Bengaluru, Karnataka')),
                ('website', models.URLField(default='www.artisanbrew.com')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('auto_disable_inactive_branches', models.BooleanField(default=False)),
                ('cross_branch_inventory_sharing', models.BooleanField(default=True)),
                ('unified_menu_across_branches', models.BooleanField(default=False)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('allow_managers_create_staff', models.BooleanField(default=True)),
                ('allow_managers_view_reports', models.BooleanField(default=False)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('invoice_footer_text', models.TextField(default='Thank you for visiting Artisan Brew!')),
                ('pm_cash', models.BooleanField(default=True)),
                ('pm_upi', models.BooleanField(default=True)),
                ('pm_card', models.BooleanField(default=True)),
                ('pm_swiggy', models.BooleanField(default=True)),
                ('pm_zomato', models.BooleanField(default=True)),
                ('notif_new_order', models.BooleanField(default=True)),
                ('notif_payment_done', models.BooleanField(default=True)),
                ('notif_low_stock', models.BooleanField(default=True)),
                ('notif_expense_added', models.BooleanField(default=False)),
                ('notif_branch_report', models.BooleanField(default=True)),
                ('notif_email_digest', models.BooleanField(default=False)),
                ('sec_two_fa', models.BooleanField(default=False)),
                ('sec_login_alerts', models.BooleanField(default=True)),
                ('sec_session_timeout', models.CharField(default='60', max_length=50)),
            ],
        ),
    ]
