# Generated by Django 6.0.6 on 2026-08-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_ownersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownersettings',
            name='website',
            field=models.URLField(blank=True, default='https://www.artisanbrew.com', null=True),
        ),
    ]
