# Generated by Django 6.0.6 on 2026-08-29 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_ownersettings_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_email', models.EmailField(blank=True, default='', max_length=254)),
                ('opening_time', models.CharField(default='09:00', max_length=20)),
                ('closing_time', models.CharField(default='23:00', max_length=20)),
                ('tax_gst', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('service_charge', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('alert_customer_assistance', models.BooleanField(default=True)),
                ('alert_bill_requests', models.BooleanField(default=True)),
                ('alert_low_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch_settings', to='accounts.branch')),
            ],
            options={
                'verbose_name': 'Branch Settings',
                'verbose_name_plural': 'Branch Settings',
            },
        ),
    ]
