# Generated by Django 6.0.6 on 2026-08-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_branchsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posterminal',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
