# Generated by Django 6.0.6 on 2026-08-31 13:08

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_adminotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('reset', 'Password Reset')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='manager_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kitchenstaff',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='posterminal',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_code', models.CharField(default=accounts.models.generate_business_code, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='branchmanager',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashiers', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='kitchenstaff',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_staff', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='waiter',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='accounts.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='branchmanager',
            unique_together={('tenant', 'manager_id')},
        ),
        migrations.AlterUniqueTogether(
            name='cashier',
            unique_together={('tenant', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='kitchenstaff',
            unique_together={('tenant', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='posterminal',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='waiter',
            unique_together={('tenant', 'employee_id')},
        ),
    ]
