# Generated by Django 6.0.6 on 2026-08-31 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_otpverification_alter_branchmanager_manager_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownersettings',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownersettings', to='accounts.tenant'),
        ),
    ]
