# Generated by Django 6.0.6 on 2026-08-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_ownersettings_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(default='BRANCH-001', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_branch_code_per_tenant'),
        ),
    ]
