# Generated by Django 6.0.6 on 2026-09-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_branch_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashier',
            unique_together={('tenant', 'branch', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='kitchenstaff',
            unique_together={('tenant', 'branch', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='waiter',
            unique_together={('tenant', 'branch', 'employee_id')},
        ),
    ]
