# Generated by Django 6.0.6 on 2026-09-01 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_cashier_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminotp',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_change_otps', to='accounts.branchmanager'),
        ),
        migrations.AddField(
            model_name='adminotp',
            name='pending_pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='branchmanager',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
