# Generated by Django 6.0.6 on 2026-09-01 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_adminotp_manager_adminotp_pending_pin_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminotp',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_change_otps', to='accounts.cashier'),
        ),
        migrations.AddField(
            model_name='adminotp',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_change_otps', to='accounts.waiter'),
        ),
    ]
