# Generated by Django 6.0.6 on 2026-08-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_accepted_at_notification_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('status_changed', 'Order Status Changed'), ('payment_completed', 'Payment Completed'), ('bill_requested', 'Bill Requested'), ('table_attention', 'Table Needs Attention'), ('bill_share', 'Bill Share Request')], db_index=True, max_length=30),
        ),
    ]
