# Generated by Django 6.0.6 on 2026-08-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_branch_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(choices=[('cashier_manager', 'Cashiers & Branch Manager'), ('manager', 'Branch Manager Only'), ('admin', 'Owner / Admin Only'), ('staff', 'Waiters / Staff Only'), ('user', 'Specific Recipient User')], db_index=True, default='cashier_manager', max_length=30),
        ),
    ]
