# Generated by Django 6.0.6 on 2026-08-31 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_otpverification_alter_branchmanager_manager_id_and_more'),
        ('notifications', '0006_notification_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.tenant'),
        ),
    ]
