# Generated by Django 6.0.6 on 2026-08-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_invoice_token_status_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_ref',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='e.g. INV-10452', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='Customer WhatsApp number (10 digits)', max_length=20),
        ),
    ]
