# Generated by Django 6.0.6 on 2026-08-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_invoice_number_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent')], default='not_sent', max_length=20),
        ),
    ]
