# Generated by Django 6.0.6 on 2026-08-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_invoice_receipt_sent_at_invoice_receipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('print', 'Print'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
