# Generated by Django 6.0.6 on 2026-08-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_invoice_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shared', 'Shared'), ('printed', 'Printed'), ('not_shared', 'Not Shared')], default='pending', max_length=20),
        ),
    ]
