# Generated by Django 6.0.6 on 2026-08-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_invoice_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='receipt_sent_at',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_method',
            field=models.CharField(choices=[('NONE', 'None'), ('WHATSAPP', 'WhatsApp'), ('PRINT', 'Print')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receipt_status',
            field=models.CharField(choices=[('NOT_SHARED', 'Not Shared'), ('SHARED', 'Shared'), ('PRINTED', 'Printed')], default='NOT_SHARED', max_length=20),
        ),
    ]
