# Generated by Django 5.2.6 on 2026-08-21 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_branch_userprofile_branch_waiter_branch'),
        ('orders', '0008_remove_invoice_receipt_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.branch'),
        ),
    ]
