# Generated by Django 6.0.6 on 2026-08-24 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_posterminal'),
        ('orders', '0011_add_bill_requested_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashier_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='pos_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.posterminal'),
        ),
    ]
