# Generated by Django 6.0.6 on 2026-08-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_cashier_name_order_pos_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('DINE_IN', 'Dine-In'), ('TAKEAWAY', 'Takeaway'), ('SWIGGY', 'Swiggy'), ('ZOMATO', 'Zomato')], db_index=True, default='DINE_IN', max_length=20),
        ),
    ]
