# Generated by Django 6.0.6 on 2026-08-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='change_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
