# Generated by Django 6.0.6 on 2026-08-31 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_otpverification_alter_branchmanager_manager_id_and_more'),
        ('orders', '0014_order_amount_received_order_change_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.tenant'),
        ),
    ]
