# Generated by Django 6.0.6 on 2026-08-13 05:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('icon', models.CharField(choices=[('coffee', 'Coffee'), ('tea', 'Tea'), ('pastry', 'Pastry'), ('dessert', 'Dessert'), ('cold', 'Cold Beverage'), ('default', 'Default')], default='default', max_length=30)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Tax / GST percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, help_text='Product photo (stored under MEDIA_ROOT/products/)', null=True, upload_to='products/')),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('available', models.BooleanField(default=True)),
                ('sold_out', models.BooleanField(default=False)),
                ('available_on_pos', models.BooleanField(default=True, help_text='Visible on POS terminal')),
                ('available_on_qr', models.BooleanField(default=True, help_text='Visible on QR digital menu')),
                ('popular', models.BooleanField(default=False, help_text='Show "Popular" badge')),
                ('featured', models.BooleanField(default=False, help_text='Featured / highlighted item')),
                ('dietary_tags', models.JSONField(blank=True, default=list, help_text='List of dietary tags, e.g. ["Vegan", "Gluten-Free"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='menu.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
