# Generated by Django 6.0.6 on 2026-08-13 06:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Table label, e.g. T-01', max_length=50, unique=True)),
                ('seats', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('bill_requested', 'Bill Requested'), ('needs_attention', 'Needs Attention')], db_index=True, default='available', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('current_order_ref', models.CharField(blank=True, default='', help_text='External order reference string', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('menu_url', models.URLField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='menu.table')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['table__name'],
            },
        ),
    ]
