# Generated by Django 5.2.6 on 2026-08-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_table_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(default='Call Waiter', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('assigned_waiter', models.CharField(blank=True, default='', max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='menu.table')),
            ],
            options={
                'verbose_name': 'Waiter Request',
                'verbose_name_plural': 'Waiter Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
