# Generated by Django 5.2.6 on 2026-08-21 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_branch_userprofile_branch_waiter_branch'),
        ('menu', '0003_waiterrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='waiterrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_requests', to='accounts.branch'),
        ),
    ]
