# Generated by Django 6.0.6 on 2026-08-24 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_inventoryitem'),
        ('orders', '0012_order_cashier_name_order_pos_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_requests', to='orders.order'),
        ),
    ]
