# Generated by Django 6.0.6 on 2026-08-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_waiterrequest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('ready', 'Ready'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], db_index=True, default='requested', max_length=20),
        ),
    ]
