# Generated by Django 6.0.6 on 2026-08-27 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_ownersettings'),
        ('menu', '0007_alter_waiterrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='accounts.branch'),
        ),
    ]
