# Generated by Django 6.0.6 on 2026-08-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_cleanup_demo_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('desserts_cake', 'Desserts — Cake'), ('desserts_cupcake', 'Desserts — Cupcake'), ('desserts_pastry', 'Desserts — Pastry'), ('meals_plate', 'Meals — Plate'), ('meals_rice', 'Meals — Rice Meal'), ('meals_thali', 'Meals — Thali'), ('juices_glass', 'Juices — Juice Glass'), ('juices_smoothie', 'Juices — Smoothie'), ('breakfast_dosa', 'Breakfast — Dosa'), ('breakfast_idli', 'Breakfast — Idli'), ('breakfast_plate', 'Breakfast — Breakfast Plate'), ('snacks_sandwich', 'Snacks — Sandwich'), ('snacks_fries', 'Snacks — Fries'), ('snacks_burger', 'Snacks — Burger'), ('dinner_plate', 'Dinner — Dinner Plate'), ('dinner_curry', 'Dinner — Curry'), ('dinner_rice', 'Dinner — Rice Dish'), ('beverages_coffee', 'Beverages — Coffee Cup'), ('beverages_tea', 'Beverages — Tea Cup'), ('beverages_drink', 'Beverages — Drink Glass'), ('bakery_bread', 'Bakery — Bread'), ('bakery_croissant', 'Bakery — Croissant'), ('bakery_pastry', 'Bakery — Pastry'), ('salads_bowl', 'Salads — Salad Bowl'), ('salads_green', 'Salads — Green Salad'), ('coffee_tea', 'Coffee & Tea'), ('pastries', 'Pastries'), ('meals', 'Meals'), ('juice', 'Juice'), ('dinner', 'Dinner'), ('breakfast', 'Breakfast'), ('snacks', 'Snacks'), ('desserts', 'Desserts'), ('default_utensils', 'Default — Utensils'), ('default_chef', 'Default — Chef Hat'), ('default', 'Default')], default='default', max_length=50),
        ),
    ]
