# Generated by Django 6.0.6 on 2026-08-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_adminotp'),
        ('menu', '0010_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(help_text='Table label, e.g. T-01', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('name', 'branch')},
        ),
    ]
