# Generated by Django 6.0.6 on 2026-08-31 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_otpverification_alter_branchmanager_manager_id_and_more'),
        ('menu', '0012_category_tenant_product_tenant_table_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='accounts.tenant'),
        ),
    ]
