# Generated by Django
from django.db import migrations

def backfill_tenant(apps, schema_editor):
    Product = apps.get_model('menu', 'Product')
    Category = apps.get_model('menu', 'Category')
    Table = apps.get_model('menu', 'Table')
    
    for model in [Product, Category, Table]:
        for obj in model.objects.filter(tenant__isnull=True, branch__isnull=False):
            obj.tenant_id = obj.branch.tenant_id
            obj.save(update_fields=['tenant'])

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_inventoryitem_tenant'),
    ]

    operations = [
        migrations.RunPython(backfill_tenant),
    ]
